name: Reload workflow

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

jobs:
  reload:
    name: Reload
    runs-on: [self-hosted, X64, Linux, 4c8g]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Reload
        uses: ./.github/actions/reload
        with:
          dsn: ${{ secrets.PERF_BENDSQL_DSN }}
          script: ${{ inputs.script }}
          warehouse: reload
          aws_key_id: ${{ secrets.REPO_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
          feishu_webhook_url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
